name: Deploy
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy TicTacNode
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST_ADDRESS }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /opt/hosted-services/Tic-Tac-Node/
            git pull
            npm install
            pm2 restart /opt/hosted-services/Tic-Tac-Node/server.js --name tictacnode
