name: Deploy application
 
on:
  push:
    branches: [ master ]
 
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy TicTacNode
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST_ADDRESS }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /opt/hosted-services/Tic-Tac-Node/
            git checkout master
            git pull
            npm install
            cd /etc/profile.d
            ./nginx_gateway.sh
            systemctl start tictacnode # start as a background service.
